### ISSUE TITLE
Image does not look good in dark theme

### ISSUE THREAD

**Issue by slavizh** [mspnp/architecture-center#1202] opened 2019-01-16 07:28 UTC
Image does not look good in dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e8dbc2-9abc-ef14-7f04-791043d69947
* Version Independent ID: 76185d93-0899-a1ba-f933-15766af2beca
* Content: [Create a financial model for cloud transformation - Enterprise Cloud Adoption](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/financial-models)
* Content Source: [docs/cloud-adoption/business-strategy/financial-models.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/business-strategy/financial-models.md)
* Service: **guidance**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment] 2019-01-16 20:45
Closing as duplicate of #1201

**Closed by mike-urnun-msft** 2019-01-16 20:45 UTC
Labels: cxp, duplicate
