### ISSUE TITLE
Add databricks

### ISSUE THREAD

**Issue by patpicos** [mspnp/architecture-center#981] opened 2018-12-02 23:53 UTC
There are no mentions of azure databricks in the comparison. Line it up with amazon emr

**Comment by mike-urnun-msft** [comment] 2018-12-06 20:22
Hello @patpicos 

Thank you for your feedback. Since this is a duplicate of #984, we will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by mike-urnun-msft** 2018-12-06 20:22 UTC
Labels: cxp, duplicate

**Comment by patpicos** [comment] 2018-12-06 20:23
thanks. i was having issues b/w the comment page and github..
